name: Embed Wikis

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (will not actually embed, just validate)'
        required: false
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  embed-wikis:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./server
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: "20"
            cache: "pnpm"
            cache-dependency-path: "./server/pnpm-lock.yaml"
    
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm prisma:generate
        env:
          EMBED_MONGODB_URI: ${{ secrets.DATABASE_URL }}

      - name: Run embed wikis script
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "Running in dry-run mode..."
            pnpm run embed:dry-run
          else
            echo "Running in normal mode..."
            pnpm run embed:dry-run
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NODE_ENV: production
